name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking=no" >> ~/.ssh/config

      - name: Prepare EC2 temp folder
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            mkdir -p /var/www/my-react-app-temp
            rm -rf /var/www/my-react-app-temp/*
          EOF

      - name: Copy build files to EC2
        run: |
          scp -r build/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/my-react-app-temp/

      - name: Deploy to production
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo rm -rf /var/www/my-react-app/*
            sudo cp -r /var/www/my-react-app-temp/* /var/www/my-react-app/
            sudo systemctl restart nginx
          EOF
